dist: focal
language: node_js
node_js:
  - lts/*
addons:
  apt:
    update: true
    packages:
      - dpkg
      - fakeroot
      - rpm
script:
  - yarn make --platform linux --arch x64
  - yarn make --platform linux --arch ia32
  - yarn make --platform linux --arch arm64
  - yarn make --platform darwin --arch x64
  - yarn make --platform darwin --arch arm64
