os:
- linux
- osx
- windows
dist: focal
language: node_js
node_js:
- lts/*
addons:
  apt:
    update: true
    packages:
    - dpkg
    - fakeroot
    - rpm
    - zip
    - unzip
before_install:
- |-
    case $TRAVIS_OS_NAME in
      windows)
        powershell Install-WindowsFeature Net-Framework-Core
        choco install -y wixtoolset
        export PATH=$PATH:"/c/Program Files (x86)/WiX Toolset v3.11/bin"
        refreshenv
        ;;
    esac
script:
- yarn make --arch x64;
- yarn make --arch arm64;
- |-
    case $TRAVIS_OS_NAME in
      windows)
        yarn make --platform win32 --arch ia32
        ;;
    esac
- cd out
- zip -r makeZipped.zip make
deploy:
  provider: releases
  api_key: $GithubOauthKey
  file: makeZipped.zip
  skip_cleanup: true
  on:
    tags: true
    all_branches: true