os:
- linux
- osx
- windows
dist: focal
language: node_js
node_js:
- lts/*
addons:
  apt:
    update: true
    packages:
    - dpkg
    - fakeroot
    - rpm
    - zip
    - unzip
env:
- YARN_GPG=no
before_install:
- |-
    case $TRAVIS_OS_NAME in
      windows)
        powershell Install-WindowsFeature Net-Framework-Core
        choco install -y wixtoolset
        export PATH=$PATH:"/c/Program Files (x86)/WiX Toolset v3.11/bin"
        ;;
    esac
script:
- yarn make --arch x64;
- yarn make --arch arm64;
- |-
    case $TRAVIS_OS_NAME in
      windows)
        yarn make --platform win32 --arch ia32
        ;;
    esac
- cd out
- |-
    case $TRAVIS_OS_NAME in
      windows)
        powershell "Compress-Archive make makeZipped-win.zip"
        ;;
    esac
- |-
    case $TRAVIS_OS_NAME in
      windows)
        powershell "move \"makeZipped-win.zip\" \"../\""
        ;;
    esac
- if ["$TRAVIS_OS_NAME" = "osx"]; then zip -r makeZipped-mac.zip make; fi
- if ["$TRAVIS_OS_NAME" = "linux"]; then zip -r makeZipped-linux.zip make; fi
- if ["$TRAVIS_OS_NAME" = "osx"]; then mv "makeZipped-mac.zip" "../"; fi
- if ["$TRAVIS_OS_NAME" = "linux"]; then mv "makeZipped-linux.zip" "../"; fi
- cd ../

deploy:
  provider: releases
  api_key: $GithubOauthKey
  file: 
    - "makeZipped-win.zip"
    - "makeZipped-mac.zip"
    - "makeZipped-linux.zip"
  skip_cleanup: true
  on:
    tags: true
    all_branches: true