dist: focal
language: node_js
script:
- yarn
- yarn make --platform linux --arch x64
- yarn make --platform linux --arch ia32
- yarn make --platform linux --arch arm64
- yarn make --platform linux --arch arm32
- yarn make --platform darwin --arch x64
- yarn make --platform darwin --arch ia32
- yarn make --platform darwin --arch arm64