dist: focal
language: node_js
node_js:
- lts/*
addons:
  apt:
    update: true
    packages:
    - dpkg
    - fakeroot
    - rpm
    - mono-complete
    - wine64
    - zip
    - unzip
script:
- yarn make --platform linux --arch x64
- yarn make --platform linux --arch arm64
- yarn make --platform darwin --arch x64
- yarn make --platform darwin --arch arm64
- cd out
- zip -r makeZipped.zip make
deploy:
  provider: releases
  api_key: $GithubOauthKey
  file: makeZipped.zip
  skip_cleanup: true
  on:
    tags: true
    all_branches: true