os:
- linux
dist: focal
- osx
- windows
language: node_js
node_js:
- lts/*
addons:
  apt:
    update: true
    packages:
    - dpkg
    - fakeroot
    - rpm
    - mono-complete
    - wine64
    - winetricks
    - zip
    - unzip
script:
- if [ "$TRAVIS_OS_NAME" = "linux" ]; yarn make --platform linux --arch x64;
- if [ "$TRAVIS_OS_NAME" = "linux" ]; yarn make --platform linux --arch arm64;
- if [ "$TRAVIS_OS_NAME" = "osx" ]; yarn make --platform darwin --arch x64;
- if [ "$TRAVIS_OS_NAME" = "osx" ]; yarn make --platform darwin --arch arm64;
- |-
    case $TRAVIS_OS_NAME in
      windows)
      yarn make --platform win32 --arch x64;
      yarn make --platform win32 --arch ia32;
      yarn make --platform win32 --arch arm64;
- cd out
- zip -r makeZipped.zip make
deploy:
  provider: releases
  api_key: $GithubOauthKey
  file: makeZipped.zip
  skip_cleanup: true
  on:
    tags: true
    all_branches: true