name: Node Build App For All Oses

on: push

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: "14.x"
      - name: Build
        shell: bash
        run: |
         if [ "$RUNNER_OS" == "Linux" ]; then
              echo "Installing Linux Dependencies"
              sudo apt-get install dpkg
              sudo apt-get install fakeroot
              sudo apt-get install rpm
              sudo apt-get install zip
              sudo apt-get install unzip
         elif [ "$RUNNER_OS" == "Windows" ]; then
              echo "Installing Windows Dependencies"
              powershell Install-WindowsFeature Net-Framework-Core
              choco install -y wixtoolset
              export PATH=$PATH:"/c/Program Files (x86)/WiX Toolset v3.11/bin"
         fi
      - name: Install Yarn Dependencies 
        shell: bash
        run: yarn install --frozen-lockfile
      - name: Make x64 and arm64 Windows Linux and MacOS
        shell: bash
        run: | 
            yarn make
            yarn make --arch arm64
      - name: Make x86 for Windows
        run: |
         if [ "$RUNNER_OS" == "Windows" ]; then
              yarn make --arch x86
         fi