name: Node Build App For Windows (x64, x86, arm64), Linux (x64, arm64), MacOS (x64, arm64)

on: push

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-10.15
          - windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: "14.x"
      - name: MacOS Fix Network Flakiness
        shell: bash
        run: |
            if [ "$RUNNER_OS" == "macOS" ]; then
              sudo sysctl -w net.link.generic.system.hwcksum_tx=0
              sudo sysctl -w net.link.generic.system.hwcksum_rx=0
            fi
            
      - name: Build
        shell: bash
        run: |
            if [ "$RUNNER_OS" == "Linux" ]; then
              echo "Installing Linux Dependencies"
              sudo apt-get install dpkg
              sudo apt-get install fakeroot
              sudo apt-get install rpm
              sudo apt-get install zip
              sudo apt-get install unzip
            elif [ "$RUNNER_OS" == "Windows" ]; then
              echo "Installing Windows Dependencies"
              powershell Install-WindowsFeature Net-Framework-Core
              choco install -y wixtoolset
              echo "C:\Program Files (x86)\WiX Toolset v3.11\bin" >> $GITHUB_PATH
            fi
      - name: Install Yarn Dependencies 
        shell: bash
        run: yarn install --frozen-lockfile
      - name: Make x64 and arm64 Windows Linux and MacOS
        shell: bash
        run: | 
            yarn make
            yarn make --arch arm64
      - name: Make x86 for Windows
        shell: bash
        run: |
            if [ "$RUNNER_OS" == "Windows" ]; then
              yarn make --arch ia32
            fi
      - name: Move Files
        shell: bash
        run: |
            mkdir Build-Artifacts
            if [ "$RUNNER_OS" == "Windows" ]; then
              pwd
              mv out/make/wix/arm64/simple-to-do-app.msi simple-to-do-app-arm64.msi
              mv out/make/wix/ia32/simple-to-do-app.msi simple-to-do-app-ia32.msi
              mv out/make/wix/x64/simple-to-do-app.msi simple-to-do-app-x64.msi
              mv out/make/wix/arm64/simple-to-do-app.msi ../../../Build-Artifacts
              mv out/make/wix/ia32/simple-to-do-app.msi ../../../Build-Artifacts
              mv out/make/wix/x64/simple-to-do-app.msi ../../../Build-Artifacts
            elif [ "$RUNNER_OS" == "Linux" ]; then
              mv out/make/deb/x64/simple-to-do-app_1.0.0_amd64.deb ../../../Build-Artifacts
              mv out/make/rpm/x64/simple-to-do-app-1.0.0-1.x86_64.rpm ../../../Build-Artifacts
              mv out/make/deb/arm64/simple-to-do-app_1.0.0_arm64.deb ../../../Build-Artifacts
              mv out/make/rpm/arm64/simple-to-do-app-1.0.0-1.arm64.rpm ../../../Build-Artifacts
            else
              ls -R
            fi