name: Node Publish App For Windows (x64, x86, arm64), Linux (x64, arm64), MacOS (x64, arm64)

on:
  push:
    tags:
    - '*'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-10.15
          - windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: "14.x"
      - name: MacOS Fix Network Flakiness
        shell: bash
        run: |
            if [ "$RUNNER_OS" == "macOS" ]; then
              sudo sysctl -w net.link.generic.system.hwcksum_tx=0
              sudo sysctl -w net.link.generic.system.hwcksum_rx=0
            fi
            
      - name: Install Dependencies
        shell: bash
        run: |
            if [ "$RUNNER_OS" == "Linux" ]; then
              echo "Installing Linux Dependencies"
              sudo apt-get install dpkg
              sudo apt-get install fakeroot
              sudo apt-get install rpm
              sudo apt-get install zip
              sudo apt-get install unzip
            elif [ "$RUNNER_OS" == "Windows" ]; then
              echo "Installing Windows Dependencies"
              powershell Install-WindowsFeature Net-Framework-Core
              choco install -y wixtoolset
              echo "C:\Program Files (x86)\WiX Toolset v3.11\bin" >> $GITHUB_PATH
            elif [ "$RUNNER_OS" == "macOS" ]; then
              brew install rename
            fi

      - name: Install Yarn Dependencies 
        shell: bash

        run: yarn install --frozen-lockfile --network-timeout 100000

      - name: Make x64, x86. and arm64 for Windows, Linux, and MacOS
        shell: bash
        run: | 
            yarn make
            yarn make --arch arm64
            if [ "$RUNNER_OS" == "Windows" ]; then
              yarn make --arch ia32
            fi
            # if [ "$RUNNER_OS" == "macOS" ]; then
            #   echo "Renaming x64 DMG"
            #   for nam in out/make/*.dmg; do echo $nam && echo mv $nam out/make/simple-to-do-app-x64.dmg && mv $nam out/make/simple-to-do-app-x64.dmg ; done
            # fi
            
            # if [ "$RUNNER_OS" == "macOS" ]; then
            #   echo "Renaming arm64 DMG"
            #   for nam in out/make/Simple To Do App-*.dmg; do mv $nam out/make/simple-to-do-app-arm64.dmg ; done
            # elif [ "$RUNNER_OS" == "Linux" ]; then
            #   for nam in out/make/simple-to-do-app_*_amd64.deb; do mv $nam out/make/simple-to-do-app_x64.deb  ; done
            #   for nam in out/make/simple-to-do-app_*_arm64.deb; do mv $nam out/make/simple-to-do-app_arm64.deb ; done
            #   for nam in out/make/simple-to-do-app-*-1.x86_64.rpm; do mv $nam out/make/simple-to-do-app-x64.rpm ; done
            #   for nam in out/make/simple-to-do-app-*-1.arm64.rpm; do mv $nam out/make/simple-to-do-app-arm64.rpm ; done  
            # fi
      - uses: actions/upload-artifact@v2
        with:
          name: Simple To Do App Windows x64 Installer
          path: |
              out/make/win32/x64/simple-to-do-app.msi
      - uses: actions/upload-artifact@v2
        with:
          name: Simple To Do App Windows x86 Installer
          path: |
              out/make/win32/ia32/simple-to-do-app.msi
      - name: Run Electron-Forge Publish
        run: yarn publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}